"""initial migration

Revision ID: 122bad81685
Revises: None
Create Date: 2014-08-26 22:47:29.215262

"""

# revision identifiers, used by Alembic.
revision = '122bad81685'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
